config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root :to => "users/sessions#new"
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :static_pages

  namespace :user do
    authenticate :user do
      resource  :user_profile
      resources :trade_win_rates, only: :index
      resources :trades do
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resource  :initialisations, only: :show
      resources :trade_win_rates, only: :index
    end
  end
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :user
  belongs_to :trade_style
  belongs_to :trade_category
  has_one_attached :image, dependent: :destroy

  validates :result,     presence: true
  validates :pips,       presence: true
  validates :entry_time, presence: true
  validates :exit_time,  presence: true

  enum result: { "資産増": 0, "変化なし": 1,"資産減": 2 }

  include Trade::Searchable

  attr_accessor :current_user_id, :year, :month_rate_year, :month

  def base64upload(file)

    return if file.blank?
    prefix = file[/(image|application)(\/.*)(?=\;)/]
    type = prefix.sub(/(image|application)(\/)/, '')
    data = Base64.decode64(file.sub(/data:#{prefix};base64,/, ''))
    filename = "#{Time.zone.now.strftime('%Y%m%d%H%M%S%L')}.#{type}"
    File.open("#{Rails.root}/tmp/#{filename}", 'wb') do |f|
      f.write(data)
    end
    image.detach if image.attached?
    image.attach(io: File.open("#{Rails.root}/tmp/#{filename}"), filename: filename)
    FileUtils.rm("#{Rails.root}/tmp/#{filename}")
    
  end

  def user_trades
    Trade.where("(user_id = ?) and (trade_category_id = ?)", current_user_id, trade_category_id)
  end

  def win_number_of_trades
    user_trades.where("result" => "資産増")
  end

  def search_trades_in_year
    from  = Time.new(year.to_i, 1, 1)
    to    = from.at_end_of_year
    Trade.where(exit_time: from..to)
  end

  def search_trades_in_month
    from  = Time.new(month_rate_year.to_i, month, 1)
    to    = from.at_end_of_month
    Trade.where(exit_time: from..to)
  end

  def user_trades_in_year
    search_trades_in_year.where("(user_id = ?) and (trade_category_id = ?)", current_user_id, trade_category_id)
  end

  def win_number_of_trades_in_year
    user_trades_in_year.where("result" => "資産増")
  end

  def user_trades_in_month
    search_trades_in_month.where("(user_id = ?) and (trade_category_id = ?)", current_user_id, trade_category_id)
  end

  def win_number_of_trades_in_month
    user_trades_in_month.where("result" => "資産増")
  end

end

app/models/trade/searchable.rb
module Trade::Searchable
  extend ActiveSupport::Concern

  included do

    scope :search_by_user_id, lambda { |user_id|
      return if user_id.blank?
      where("trades.user_id" => user_id)
    }

    scope :search_by_trade_category, lambda { |trade_category_id|
      return if trade_category_id.blank?
      where("trades.trade_category_id" => trade_category_id)
    }

    scope :search_by_trade_style, lambda { |trade_style_id|
      return if trade_style_id.blank?
      where("trades.trade_style_id" => trade_style_id)
    }

    scope :search_by_min_pips, lambda { |min_pips|
      return if min_pips.blank?
      result_trade_ids = Trade.ids.select do |trade_id|
        Trade.find(trade_id).pips >= min_pips.to_i
      end
      where(id: result_trade_ids)
    }

    scope :search_by_max_pips, lambda { |max_pips|
      return if max_pips.blank?
      result_trade_ids = Trade.ids.select do |trade_id|
        Trade.find(trade_id).pips <= max_pips.to_i
      end
      where(id: result_trade_ids)
    }

    scope :search_by_upper_entry_time, lambda { |min_entry_time|
      return if min_entry_time.blank?
      where(arel_table[:entry_time].gteq(min_entry_time))
    }

    scope :search_by_lower_entry_time, lambda { |max_entry_time|
      return if max_entry_time.blank?
      where(arel_table[:entry_time].lteq(max_entry_time))
    }

    scope :search_by_upper_exit_time, lambda { |min_exit_time|
      return if min_exit_time.blank?
      where(arel_table[:exit_time].gteq(min_exit_time))
    }

    scope :search_by_lower_exit_time, lambda { |max_exit_time|
      return if max_exit_time.blank?
      where(arel_table[:exit_time].lteq(max_exit_time))
    }

    scope :search_by_result, lambda { |result|
      return if result.blank?
      where("trades.result" => result)
    }
    
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one  :user_profile, dependent: :destroy
  has_many :trades, dependent: :destroy

  validates_format_of :password, with: /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[A-Za-z\d]{8,100}\z/
end

app/controllers/user/application_controller.rb
class User::ApplicationController < ApplicationController
  layout 'user/application.html.erb'
end

app/controllers/user/trade_win_rates_controller.rb
class User::TradeWinRatesController < User::ApplicationController

  def index
    year              = params[:trade_win_rate].nil? || params[:trade_win_rate][:year].nil? ? Time.now.strftime("%Y") : params[:trade_win_rate][:year]
    month_rate_year   = params[:trade_win_rate].nil? || params[:trade_win_rate][:month_rate_year].nil? ? Time.now.strftime("%Y") : params[:trade_win_rate][:month_rate_year]
    month             = params[:trade_win_rate].nil? || params[:trade_win_rate][:month].nil? ? Time.now.strftime("%m").delete("0") : params[:trade_win_rate][:month]
    @fx               = TradeWinRate.new(current_user_id: current_user.id, trade_category_id: 1, year: year)
    @stock            = TradeWinRate.new(current_user_id: current_user.id, trade_category_id: 2, year: year)
    @virtual_currency = TradeWinRate.new(current_user_id: current_user.id, trade_category_id: 3, year: year)
    @fx_in_month      = TradeWinRate.new(current_user_id: current_user.id, trade_category_id: 1, month_rate_year: month_rate_year, month: month)
    @stock_in_month   = TradeWinRate.new(current_user_id: current_user.id, trade_category_id: 2, month_rate_year: month_rate_year, month: month)
    @virtual_currency_in_month = TradeWinRate.new(current_user_id: current_user.id, trade_category_id: 3, month_rate_year: month_rate_year, month: month)
  end

end

app/controllers/user/trades_controller.rb
class User::TradesController < User::ApplicationController
  before_action :set_trade_params, only: [:show, :edit, :update, :destroy]
  before_action :trade_user?,      only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => [:create, :update]

  def index
    @trade_search_form = TradeSearchForm.new(trade_search_params)
    @trade_search_form.user_id = current_user.id
    @trades = @trade_search_form.search
              .order(id: :desc)
              .page(params[:page])
              .per(4)
  end

  def new
    @trade = Trade.new
  end

  def create
    @trade = Trade.new(trade_params.except(:image))
    @trade.base64upload(trade_params[:image])
    respond_to do |format|
      if @trade.save
        format.html 
        format.json { render json: @trade, status: :created}
      else
        format.html
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  def show;end

  def edit
    respond_to do |format|
      format.html
      format.json { render :json => { trade: @trade } }
    end
  end

  def update
    respond_to do |format|
      if trade_params.present?
        @trade.update(trade_params.except(:image))
        @trade.base64upload(trade_params[:image])
        @trade.update(trade_params)
        format.html 
        format.json { render json: @trade, status: :created}
      else
        format.html
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @trade.destroy
        format.html
        format.json { render json: @trade, status: :ok }
      else
        format.html
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_trade_params
    @trade = Trade.find(params[:id])
  end

  def trade_user?
    unless @trade.user === current_user
      redirect_to user_trades_path
    end
  end

  def trade_params
    params.require(:trade).permit(
      :trade_style_id, :trade_category_id, :pips,       :content,
      :entry_time,     :exit_time,         :result,     :user_id,
      :image,          :created_at,        :updated_at, :id
    )
  end

  def trade_search_params
    return if params[:trade_search_form].blank?
    params.require(:trade_search_form).permit(
      :trade_category_id, :trade_style_id,  :min_pips,      :max_pips,
      :min_entry_time,    :max_entry_time,  :min_exit_time, :max_exit_time,
      :result,            :user_id
    )
  end

end

app/controllers/user/user_profiles_controller.rb
class User::UserProfilesController < User::ApplicationController
  protect_from_forgery :except => [:create, :update]

  def new
    @user_profile = UserProfile.new
  end

  def create
    @user_profile = current_user.build_user_profile(user_profile_params.except(:avatar))
    @user_profile.base64upload(user_profile_params[:avatar])
    respond_to do |format|
      if @user_profile.save
        format.html
        format.json { render json: @user_profile, status: :created}
      else
        format.html
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user_profile = current_user.user_profile
    respond_to do |format|
      format.html
      format.json { render json: { user_profile: @user_profile} }
    end
  end

  def update
    @user_profile = current_user.user_profile
    respond_to do |format|
      if user_profile_params.present?
        @user_profile.update(user_profile_params.except(:avatar))
        @user_profile.base64upload(user_profile_params[:avatar])
        @user_profile.update(user_profile_params)
        format.html
        format.json { render json: @user_profile,  status: :created }
      else
        format.html
        format.json { render json: @user_profile_params.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_profile_params
    params.require(:user_profile).permit(:nickname, :avatar, :id, :user_id, :created_at, :updated_at)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  layout 'user/application.html.erb'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout 'user/application.html.erb'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_user_user_profile_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'user/application.html.erb'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(resource)
    user_trades_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/trades/edit.html.erb
<div class="mt-5" id="trade">
  <notifications group="information"></notifications>
  <div class="row">
    <%= render "shared/user/left_side_bar" %>
    <div class="col-10 col-lg-7 mb-5 c-trade-form">
      <div class="row">
        <div class="col-12">
          <label>トレードスタイル</label>
          <select v-model="trade.trade_style_id" placeholder="トレードスタイル" class="form-control">
            <option
              v-for="trade_style in trade_styles"
              :key="trade_style.id"
              :label="trade_style.name"
              :value="trade_style.id"
            >
            </option>
          </select>
        </div>
        <div class="col-12">
          <label>カテゴリー</label>
          <select v-model="trade.trade_category_id" placeholder="トレードカテゴリ" class="form-control">
            <option
              v-for="trade_category in trade_categories"
              :key="trade_category.id"
              :label="trade_category.name"
              :value="trade_category.id"
            >
            </option>
          </select>
        </div>
        <div class="col-12">
          <label>エントリー日時</label>
          <input v-model="trade.entry_time" type="date" class="form-control">
        </div>
        <div class="col-12">
          <label>決済日時</label>
          <input v-model="trade.exit_time" type="date" class="form-control">
        </div>
        <div class="col-12">
          <label>Pips</label>
          <input placeholder="pips" v-model="trade.pips" class="form-control">
        </div>
        <div class="col-12">
          <label>結果</label>
          <select placeholder="result" v-model="trade.result" class="form-control">
            <option
              v-for="result in results"
              :key="result"
              :label="result"
              :value="result"
            >
            </option>
          </select>
        </div>
        <div class="col-12">
          <label>画像</label>
          <label for="file_upload">
            <div v-if="changeImage">
              <%= image_tag @trade.image if @trade.image.attached? %>
              <input name="uploadedImage" class="mt-3 d-none" type="file" ref="file" accept="image/*" @change="selectImage" id="file_upload">
            </div>
            <div v-else>
              <img :src="trade_image" class="w-100">
              <input name="uploadedImage" class="mt-3 d-none" type="file" ref="file" accept="image/*" @change="selectImage" id="file_upload">
            </div>
          </label>
        </div>
        <div class="col-12">
           <label>メモ</label>
          <textarea placeholder="エントリーした理由などを記述" v-model="trade.content"></textarea>
        </div>
        <div class="col-12 text-center mt-3">
          <button class="btn c-devise-form__submit-btn" @click="update(trade.id)" enctype="multipart/form-data">
            内容を変更する
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_packs_with_chunks_tag 'user/trade_edit' %>

app/views/user/trades/index.html.erb
<div class="row">
  <div class="col-12 p-trade mt-4 mt-sm-5">
    <div class="row">
      <%= render "shared/user/left_side_bar" %>
      <div class="col-12 col-lg-9">
        <div class="row">
          <%= render "shared/public/search_box" %>
          <% if @trades.present? %>
            <% @trades.each do |trade| %>
              <div class="col-11 col-sm-5 p-trade__card mb-5">
                <%= link_to user_trade_path(trade) do %>
                  <div>
                    <%= image_tag trade.image, class: "p-trade__card-image" %>
                  </div>
                  <div class="p-trade__card-content">
                    <div>
                      <p>カテゴリー： <%= trade.trade_category.name %></p>
                    </div>
                    <div>
                      <p>スタイル： <%= trade.trade_style.name %></p>
                    </div>
                    <div>
                      <p>Pips： <%= trade.pips %></p>
                    </div>
                    <div>
                      <p>エントリー： <%= trade.entry_time.strftime("%Y年 %m月%d日") %></p>
                    </div>
                    <div>
                      <p>決済： <%= trade.exit_time.strftime("%Y年 %m月%d日") %></p>
                    </div>
                    <div>
                      <p>結果： <%= trade.result %></p>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% else %>
            <div class="col-10 col-sm-8 col-xl-7 text-center mx-auto">
              <p><span class="text-danger">＊トレードの記録がありません！</span></p>
              <%= link_to "トレードの記録を残す", new_user_trade_path, class: "btn c-devise-form__submit-btn text-white" %>
            </div>
          <% end %>
          <div class="col-12 text-center">
            <%= paginate @trades %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/trades/new.html.erb
<div class="mt-5" id="trade">
  <notifications group="information"></notifications>
  <div class="row">
    <%= render "shared/user/left_side_bar" %>
    <div class="col-10 col-lg-7 mb-5 c-trade-form">
      <div class="row">
        <div class="col-12">
          <label>トレードスタイル</label>
          <select v-model="trade.trade_style_id" placeholder="トレードスタイル" class="form-control">
            <option
              v-for="trade_style in trade_styles"
              :key="trade_style.id"
              :label="trade_style.name"
              :value="trade_style.id"
            >
            </option>
          </select>
        </div>
        <div class="col-12">
          <label>カテゴリー</label>
          <select v-model="trade.trade_category_id" placeholder="トレードカテゴリ" class="form-control">
            <option
              v-for="trade_category in trade_categories"
              :key="trade_category.id"
              :label="trade_category.name"
              :value="trade_category.id"
            >
            </option>
          </select>
        </div>
        <div class="col-12">
          <label>エントリー日時</label>
          <input v-model="trade.entry_time" type="date" class="form-control">
        </div>
        <div class="col-12">
          <label>決済日時</label>
          <input v-model="trade.exit_time" type="date" class="form-control">
        </div>
        <div class="col-12">
          <label>Pips</label>
          <input placeholder="pips" v-model="trade.pips" class="form-control">
        </div>
        <div class="col-12">
          <label>結果</label>
          <select placeholder="result" v-model="trade.result" class="form-control">
            <option
              v-for="result in results"
              :key="result"
              :label="result"
              :value="result"
            >
            </option>
          </select>
        </div>
        <div class="col-12">
          <label>画像</label>
          <label for="file_upload">
            <img :src="trade_image" class="w-100">
            <input name="uploadedImage" class="mt-3 d-none" type="file" ref="file" accept="image/*" @change="selectImage" id="file_upload">
          </label>
        </div>
        <div class="col-12">
           <label>メモ</label>
          <textarea placeholder="エントリーした理由などを記述" v-model="trade.content"></textarea>
        </div>
        <div class="col-12 text-center mt-3">
          <button class="btn c-devise-form__submit-btn" @click="submit" enctype="multipart/form-data">
            記録する
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_packs_with_chunks_tag 'user/trade_new' %>

app/views/user/trades/show.html.erb
<div class="mt-5" id="trade">
  <notifications group="information"></notifications>
  <div class="row">
    <%= render "shared/user/left_side_bar" %>
    <div class="col-8 col-lg-6 p-trade__card">
      <div>
        <%= image_tag @trade.image, class: "p-trade__card-image" %>
      </div>
      <div class="p-trade__card-content">
        <div>
          <p>カテゴリー： <%= @trade.trade_category.name %></p>
        </div>
        <div>
          <p>スタイル： <%= @trade.trade_style.name %></p>
        </div>
        <div>
          <p>Pips： <%= @trade.pips %></p>
        </div>
        <div>
          <p>エントリー： <%= @trade.entry_time.strftime("%Y年 %m月%d日") %></p>
        </div>
        <div>
          <p>決済： <%= @trade.exit_time.strftime("%Y年 %m月%d日") %></p>
        </div>
        <div>
          <p>結果： <%= @trade.result %></p>
        </div>
        <div>
          <p>メモ</p>
          <textarea><%= @trade.content %></textarea>
        </div>
        <div class="row">
          <div class="col-6">
            <button class="btn p-trade__card__delete-btn mt-4" @click="destroy(trade.id)">
              削除
            </button>
          </div>
          <div class="col-6">
            <%= link_to edit_user_trade_path, class: "btn c-devise-form__submit-btn mt-4" do %>
              編集
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_packs_with_chunks_tag 'user/trade_edit' %>