config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root :to => "users/sessions#new"
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :static_pages

  namespace :user do
    authenticate :user do
      resource  :user_profile
      resources :trade_win_rates, only: :index
      resources :trades do
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resource  :initialisations, only: :show
      resources :trade_win_rates, only: :index
    end
  end
end

app/models/trade_win_rate.rb
class TradeWinRate < Trade
  attr_accessor :trade_category_id
  def total_win_rate
    return "0%" if win_number_of_trades.count === 0
    "#{(win_number_of_trades.count / user_trades.count.to_f * 100).floor(1)}%"
  end

  def trade_style_win_rate(trade_style_id)
    return "0%" if win_number_of_trades.count === 0
    trades = win_number_of_trades.where("trade_style_id" => trade_style_id).count
    "#{(trades / user_trades.count.to_f * 100).floor(1)}%"
  end

  def total_win_rate_in_year
    return "0%" if win_number_of_trades_in_year.count === 0
    "#{(win_number_of_trades_in_year.count / user_trades_in_year.count.to_f * 100).floor(1)}%"
  end

  def trade_style_win_rate_in_year(trade_style_id)
    return "0%" if win_number_of_trades_in_year.count === 0
    trades = win_number_of_trades_in_year.where("trade_style_id" => trade_style_id).count
    "#{(trades / user_trades_in_year.count.to_f * 100).floor(1)}%"
  end

  def total_win_rate_in_month
    return "0%" if win_number_of_trades_in_month.count === 0
    "#{(win_number_of_trades_in_month.count / user_trades_in_month.count.to_f * 100).floor(1)}%"
  end

  def trade_style_win_rate_in_month(trade_style_id)
    return "0%" if win_number_of_trades_in_month.count === 0
    trades = win_number_of_trades_in_month.where("trade_style_id" => trade_style_id).count
    "#{(trades / user_trades_in_month.count.to_f * 100).floor(1)}%"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one  :user_profile, dependent: :destroy
  has_many :trades, dependent: :destroy

  validates_format_of :password, with: /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[A-Za-z\d]{8,100}\z/
end

app/controllers/api/v1/trade_win_rates_controller.rb
class Api::V1::TradeWinRatesController < Api::V1::ApplicationController

  def index
    @fx = Trade
          .search_by_user_id(current_user)
          .search_by_trade_category(1)
          .search_by_result("資産増")

    @stock = Trade
             .search_by_user_id(current_user)
             .search_by_trade_category(2)
             .search_by_result("資産増")

    @virtual_currency = Trade
                        .search_by_user_id(current_user)
                        .search_by_trade_category(3)
                        .search_by_result("資産増")
    respond_to do |format|
      format.json {render :json =>
        {
          fx: @fx,
          stock: @stock,
          virtual_currency: @virtual_currency
        }
      }
    end
  end

end

app/controllers/user/application_controller.rb
class User::ApplicationController < ApplicationController
  layout 'user/application.html.erb'
end

app/controllers/user/trade_win_rates_controller.rb
class User::TradeWinRatesController < User::ApplicationController

  def index
    year              = params[:trade_win_rate].nil? || params[:trade_win_rate][:year].nil? ? Time.now.strftime("%Y") : params[:trade_win_rate][:year]
    month_rate_year   = params[:trade_win_rate].nil? || params[:trade_win_rate][:month_rate_year].nil? ? Time.now.strftime("%Y") : params[:trade_win_rate][:month_rate_year]
    month             = params[:trade_win_rate].nil? || params[:trade_win_rate][:month].nil? ? Time.now.strftime("%m").delete("0") : params[:trade_win_rate][:month]
    @fx               = TradeWinRate.new(current_user_id: current_user.id, trade_category_id: 1, year: year)
    @stock            = TradeWinRate.new(current_user_id: current_user.id, trade_category_id: 2, year: year)
    @virtual_currency = TradeWinRate.new(current_user_id: current_user.id, trade_category_id: 3, year: year)
    @fx_in_month      = TradeWinRate.new(current_user_id: current_user.id, trade_category_id: 1, month_rate_year: month_rate_year, month: month)
    @stock_in_month   = TradeWinRate.new(current_user_id: current_user.id, trade_category_id: 2, month_rate_year: month_rate_year, month: month)
    @virtual_currency_in_month = TradeWinRate.new(current_user_id: current_user.id, trade_category_id: 3, month_rate_year: month_rate_year, month: month)
  end

end

app/controllers/user/trades_controller.rb
class User::TradesController < User::ApplicationController
  before_action :set_trade_params, only: [:show, :edit, :update, :destroy]
  before_action :trade_user?,      only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => [:create, :update]

  def index
    @trade_search_form = TradeSearchForm.new(trade_search_params)
    @trade_search_form.user_id = current_user.id
    @trades = @trade_search_form.search
              .order(id: :desc)
              .page(params[:page])
              .per(4)
  end

  def new
    @trade = Trade.new
  end

  def create
    @trade = Trade.new(trade_params.except(:image))
    @trade.base64upload(trade_params[:image])
    respond_to do |format|
      if @trade.save
        format.html 
        format.json { render json: @trade, status: :created}
      else
        format.html
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  def show;end

  def edit
    respond_to do |format|
      format.html
      format.json { render :json => { trade: @trade } }
    end
  end

  def update
    respond_to do |format|
      if trade_params.present?
        @trade.update(trade_params.except(:image))
        @trade.base64upload(trade_params[:image])
        @trade.update(trade_params)
        format.html 
        format.json { render json: @trade, status: :created}
      else
        format.html
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @trade.destroy
        format.html
        format.json { render json: @trade, status: :ok }
      else
        format.html
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_trade_params
    @trade = Trade.find(params[:id])
  end

  def trade_user?
    unless @trade.user === current_user
      redirect_to user_trades_path
    end
  end

  def trade_params
    params.require(:trade).permit(
      :trade_style_id, :trade_category_id, :pips,       :content,
      :entry_time,     :exit_time,         :result,     :user_id,
      :image,          :created_at,        :updated_at, :id
    )
  end

  def trade_search_params
    return if params[:trade_search_form].blank?
    params.require(:trade_search_form).permit(
      :trade_category_id, :trade_style_id,  :min_pips,      :max_pips,
      :min_entry_time,    :max_entry_time,  :min_exit_time, :max_exit_time,
      :result,            :user_id
    )
  end

end

app/controllers/user/user_profiles_controller.rb
class User::UserProfilesController < User::ApplicationController
  protect_from_forgery :except => [:create, :update]

  def new
    @user_profile = UserProfile.new
  end

  def create
    @user_profile = current_user.build_user_profile(user_profile_params.except(:avatar))
    @user_profile.base64upload(user_profile_params[:avatar])
    respond_to do |format|
      if @user_profile.save
        format.html
        format.json { render json: @user_profile, status: :created}
      else
        format.html
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user_profile = current_user.user_profile
    respond_to do |format|
      format.html
      format.json { render json: { user_profile: @user_profile} }
    end
  end

  def update
    @user_profile = current_user.user_profile
    respond_to do |format|
      if user_profile_params.present?
        @user_profile.update(user_profile_params.except(:avatar))
        @user_profile.base64upload(user_profile_params[:avatar])
        @user_profile.update(user_profile_params)
        format.html
        format.json { render json: @user_profile,  status: :created }
      else
        format.html
        format.json { render json: @user_profile_params.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_profile_params
    params.require(:user_profile).permit(:nickname, :avatar, :id, :user_id, :created_at, :updated_at)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  layout 'user/application.html.erb'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout 'user/application.html.erb'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_user_user_profile_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'user/application.html.erb'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(resource)
    user_trades_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/trade_win_rates/_month_win_rate.html.erb
<div class="col-12">
  <div class="mt-5 d-xl-flex justify-content-between">
    <p class="font-weight-bold mb-3 m-0">月間勝率</p>
    <%= form_with model: [:user, @fx_in_month], url: user_trade_win_rates_path, method: :get, local: true do |f| %>
      <div class="d-md-flex form-group">
        <div class="d-flex form-group">
          <%= f.number_field :month_rate_year, class: "form-control" %>
          <div class="mr-1 ml-1 mt-1 h5">/</div>
          <%= f.number_field :month, class: "form-control" %>
        </div>
        <div class="d-flex form-group">
          <%= f.submit "この月で検索", class: "btn c-devise-form__submit-btn ml-md-3" %>
          <%= link_to "リセット", user_trade_win_rates_path, class: "btn p-trade__card__delete-btn bg-black text-white ml-3" %>
        </div>
      </div>
    <% end %>
  </div>
  <% if @fx_in_month.user_trades_in_month.present? %>
    <div class="d-flex justify-content-between mt-3">
      <p class="m-0 mr-5">Fx トレード数 <%= @fx_in_month.user_trades_in_month.count %></p>
      <p class="m-0 ml-5">
        <span v-if="displayWinRate[0]" @click="toggleDisplayWinRate(0)">
          非表示
        </span>
        <span v-else @click="toggleDisplayWinRate(0)">
          表示
        </span>
      </p>
    </div>
    <table class="d-none" :class="{ 'd-block' : displayWinRate[0] }">
      <tr>
        <th>全体</th>
        <th>デイ</th>
        <th>スイング</th>
        <th>スキャル</th>
      </tr>

      <tr>
        <td><%= @fx_in_month.total_win_rate_in_month %></td>
        <td><%= @fx_in_month.trade_style_win_rate_in_month(1) %></td>
        <td><%= @fx_in_month.trade_style_win_rate_in_month(2) %></td>
        <td><%= @fx_in_month.trade_style_win_rate_in_month(3) %></td>
      </tr>

    </table>
  <% end %>

  <% if @stock_in_month.user_trades_in_month.present? %>
    <div class="d-flex justify-content-between mt-3">
      <p class="m-0 mr-5">株 トレード数 <%=@stock_in_month.user_trades_in_month.count %></p>
      <p class="m-0 ml-5">
        <span v-if="displayWinRate[1]" @click="toggleDisplayWinRate(1)">
          非表示
        </span>
        <span v-else @click="toggleDisplayWinRate(1)">
          表示
        </span>
      </p>
    </div>
    <table class="d-none" :class="{ 'd-block' : displayWinRate[1] }">
      <tr>
        <th>全体</th>
        <th>デイ</th>
        <th>スイング</th>
        <th>スキャル</th>
      </tr>

      <tr>
        <td><%=@stock_in_month.total_win_rate_in_month %></td>
        <td><%=@stock_in_month.trade_style_win_rate_in_month(1) %></td>
        <td><%=@stock_in_month.trade_style_win_rate_in_month(2) %></td>
        <td><%=@stock_in_month.trade_style_win_rate_in_month(3) %></td>
      </tr>

    </table>
  <% end %>

  <% if @virtual_currency_in_month.user_trades_in_month.present? %>
    <div class="d-flex justify-content-between mt-3">
      <p class="m-0">仮想通貨 トレード数 <%= @virtual_currency_in_month.user_trades_in_month.count %></p>
      <p class="m-0 ml-5">
        <span v-if="displayWinRate[2]" @click="toggleDisplayWinRate(2)">
          非表示
        </span>
        <span v-else @click="toggleDisplayWinRate(2)">
          表示
        </span>
      </p>
    </div>
    <table class="d-none" :class="{ 'd-block' : displayWinRate[2] }">
      <tr>
        <th>全体</th>
        <th>デイ</th>
        <th>スイング</th>
        <th>スキャル</th>
      </tr>

      <tr>
        <td><%= @virtual_currency_in_month.total_win_rate_in_month %></td>
        <td><%= @virtual_currency_in_month.trade_style_win_rate_in_month(1) %></td>
        <td><%= @virtual_currency_in_month.trade_style_win_rate_in_month(2) %></td>
        <td><%= @virtual_currency_in_month.trade_style_win_rate_in_month(3) %></td>
      </tr>

    </table>
  <% end %>
</div>

app/views/user/trade_win_rates/_total_win_rate.html.erb
<div class="col-12">
  <div>
    <p class="font-weight-bold m-0">全体勝率</p>
  </div>
  <% if @fx.user_trades.present? %>
    <div class="d-flex justify-content-between mt-3">
      <p class="m-0 mr-5">Fx トレード数 <%= @fx.user_trades.count %></p>
      <p class="m-0 ml-5">
        <span v-if="displayWinRate[0]" @click="toggleDisplayWinRate(0)">
          非表示
        </span>
        <span v-else @click="toggleDisplayWinRate(0)">
          表示
        </span>
      </p>
    </div>
    <table class="d-none" :class="{ 'd-block' : displayWinRate[0] }">
      <tr>
        <th>全体</th>
        <th>デイ</th>
        <th>スイング</th>
        <th>スキャル</th>
      </tr>

      <tr>
        <td><%= @fx.total_win_rate %></td>
        <td><%= @fx.trade_style_win_rate(1) %></td>
        <td><%= @fx.trade_style_win_rate(2) %></td>
        <td><%= @fx.trade_style_win_rate(3) %></td>
      </tr>

    </table>
  <% end %>

  <% if @stock.user_trades.present? %>
    <div class="d-flex justify-content-between mt-3">
      <p class="m-0 mr-5">株 トレード数 <%= @stock.user_trades.count %></p>
      <p class="m-0 ml-5">
        <span v-if="displayWinRate[1]" @click="toggleDisplayWinRate(1)">
          非表示
        </span>
        <span v-else @click="toggleDisplayWinRate(1)">
          表示
        </span>
      </p>
    </div>
    <table class="d-none" :class="{ 'd-block' : displayWinRate[1] }">
      <tr>
        <th>全体</th>
        <th>デイ</th>
        <th>スイング</th>
        <th>スキャル</th>
      </tr>

      <tr>
        <td><%= @stock.total_win_rate %></td>
        <td><%= @stock.trade_style_win_rate(1) %></td>
        <td><%= @stock.trade_style_win_rate(2) %></td>
        <td><%= @stock.trade_style_win_rate(3) %></td>
      </tr>

    </table>
  <% end %>

  <% if @virtual_currency.user_trades.present? %>
    <div class="d-flex justify-content-between mt-3">
      <p class="m-0">仮想通貨 トレード数 <%= @virtual_currency.user_trades.count %></p>
      <p class="m-0 ml-5">
        <span v-if="displayWinRate[2]" @click="toggleDisplayWinRate(2)">
          非表示
        </span>
        <span v-else @click="toggleDisplayWinRate(2)">
          表示
        </span>
      </p>
    </div>
    <table class="d-none" :class="{ 'd-block' : displayWinRate[2] }">
      <tr>
        <th>全体</th>
        <th>デイ</th>
        <th>スイング</th>
        <th>スキャル</th>
      </tr>

      <tr>
        <td><%= @virtual_currency.total_win_rate %></td>
        <td><%= @virtual_currency.trade_style_win_rate(1) %></td>
        <td><%= @virtual_currency.trade_style_win_rate(2) %></td>
        <td><%= @virtual_currency.trade_style_win_rate(3) %></td>
      </tr>

    </table>
  <% end %>
</div>

app/views/user/trade_win_rates/_year_win_rate.html.erb
<div class="col-12">
  <div class="mt-5 d-md-flex justify-content-between">
    <p class="font-weight-bold mb-3 m-0">年内勝率</p>
    <%= form_with model: [:user, @fx], url: user_trade_win_rates_path, method: :get, local: true do |f| %>
      <div class="d-flex form-group">
        <%= f.number_field :year, class: "form-control" %>
        <%= f.submit "この年で検索", class: "btn c-devise-form__submit-btn ml-3" %>
        <%= link_to "リセット", user_trade_win_rates_path, class: "btn p-trade__card__delete-btn bg-black text-white ml-3" %>
      </div>
    <% end %>
  </div>
  <% if @fx.user_trades_in_year.present? %>
    <div class="d-flex justify-content-between mt-3">
      <p class="m-0 mr-5">Fx トレード数 <%= @fx.user_trades_in_year.count %></p>
      <p class="m-0 ml-5">
        <span v-if="displayWinRate[0]" @click="toggleDisplayWinRate(0)">
          非表示
        </span>
        <span v-else @click="toggleDisplayWinRate(0)">
          表示
        </span>
      </p>
    </div>
    <table class="d-none" :class="{ 'd-block' : displayWinRate[0] }">
      <tr>
        <th>全体</th>
        <th>デイ</th>
        <th>スイング</th>
        <th>スキャル</th>
      </tr>

      <tr>
        <td><%= @fx.total_win_rate_in_year %></td>
        <td><%= @fx.trade_style_win_rate_in_year(1) %></td>
        <td><%= @fx.trade_style_win_rate_in_year(2) %></td>
        <td><%= @fx.trade_style_win_rate_in_year(3) %></td>
      </tr>

    </table>
  <% end %>

  <% if @stock.user_trades_in_year.present? %>
    <div class="d-flex justify-content-between mt-3">
      <p class="m-0 mr-5">株 トレード数 <%= @stock.user_trades_in_year.count %></p>
      <p class="m-0 ml-5">
        <span v-if="displayWinRate[1]" @click="toggleDisplayWinRate(1)">
          非表示
        </span>
        <span v-else @click="toggleDisplayWinRate(1)">
          表示
        </span>
      </p>
    </div>
    <table class="d-none" :class="{ 'd-block' : displayWinRate[1] }">
      <tr>
        <th>全体</th>
        <th>デイ</th>
        <th>スイング</th>
        <th>スキャル</th>
      </tr>

      <tr>
        <td><%= @stock.total_win_rate_in_year %></td>
        <td><%= @stock.trade_style_win_rate_in_year(1) %></td>
        <td><%= @stock.trade_style_win_rate_in_year(2) %></td>
        <td><%= @stock.trade_style_win_rate_in_year(3) %></td>
      </tr>

    </table>
  <% end %>

  <% if @virtual_currency.user_trades_in_year.present? %>
    <div class="d-flex justify-content-between mt-3">
      <p class="m-0">仮想通貨 トレード数 <%= @virtual_currency.user_trades_in_year.count %></p>
      <p class="m-0 ml-5">
        <span v-if="displayWinRate[2]" @click="toggleDisplayWinRate(2)">
          非表示
        </span>
        <span v-else @click="toggleDisplayWinRate(2)">
          表示
        </span>
      </p>
    </div>
    <table class="d-none" :class="{ 'd-block' : displayWinRate[2] }">
      <tr>
        <th>全体</th>
        <th>デイ</th>
        <th>スイング</th>
        <th>スキャル</th>
      </tr>

      <tr>
        <td><%= @virtual_currency.total_win_rate_in_year %></td>
        <td><%= @virtual_currency.trade_style_win_rate_in_year(1) %></td>
        <td><%= @virtual_currency.trade_style_win_rate_in_year(2) %></td>
        <td><%= @virtual_currency.trade_style_win_rate_in_year(3) %></td>
      </tr>

    </table>
  <% end %>
</div>

app/views/user/trade_win_rates/index.html.erb
<div class="row p-win-rate" id="win_rate">
  <div class="col-12 p-trade mt-4 mt-sm-5">
     <div class="row">
      <%= render "shared/user/left_side_bar" %>
      <div class="col-12 col-lg-9 p-win-rate__table">
        <%= render "total_win_rate" %>
        <%= render "year_win_rate" %>
        <%= render "month_win_rate" %>
      </div>
    </div>
  </div>
</div>

<%= javascript_packs_with_chunks_tag 'user/win_rate' %>